package com.northstar.funding.kafka.events;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.UUID;

/**
 * Event representing a search request to be executed.
 *
 * <p>Published to: {@code search-requests} topic
 * <p>Published by: SearchController (REST API)
 * <p>Consumed by: SearchRequestConsumer
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SearchRequestEvent {

    /**
     * Unique identifier for this search request.
     * Used for tracking workflow progress and correlating events.
     */
    private UUID requestId;

    /**
     * Discovery session ID for grouping related searches.
     */
    private UUID sessionId;

    /**
     * Search query text generated by QueryGenerationService.
     */
    private String query;

    /**
     * Search engine to use for executing this query.
     * Maps to SearchEngineType enum in domain module.
     */
    private String searchEngine;

    /**
     * Maximum number of results to retrieve.
     * Typically 20-25 results per query.
     */
    private int maxResults;

    /**
     * Timestamp when request was created.
     */
    private Instant timestamp;

    /**
     * Funding category for context (optional).
     * Example: INFRASTRUCTURE_FUNDING, TEACHER_DEVELOPMENT
     */
    private String category;

    /**
     * Geographic scope for context (optional).
     * Example: BULGARIA, BALKANS, EASTERN_EUROPE
     */
    private String geographic;
}
