package com.northstar.funding.searchadapters.model;

import com.northstar.funding.domain.SearchEngineType;
import lombok.Builder;
import lombok.Data;

import java.time.Duration;
import java.util.List;
import java.util.Map;

/**
 * Result model for search workflow execution.
 *
 * <p>Contains comprehensive statistics about a completed search workflow,
 * including query generation, search execution, result processing, and
 * candidate creation metrics.
 *
 * <p>Used for monitoring, logging, and effectiveness tracking.
 *
 * <p>Example usage:
 * <pre>{@code
 * SearchWorkflowResult result = workflowService.executeManualSearch(request);
 *
 * System.out.println("Session ID: " + result.getSessionId());
 * System.out.println("Queries generated: " + result.getQueriesGenerated());
 * System.out.println("Candidates created: " + result.getCandidatesCreated());
 * System.out.println("Execution time: " + result.getExecutionDuration().toMinutes() + " minutes");
 *
 * if (result.isHasFailures()) {
 *     System.err.println("Failures: " + result.getFailureMessages());
 * }
 * }</pre>
 */
@Data
@Builder
public class SearchWorkflowResult {

    /**
     * Discovery session ID (database primary key).
     * References discovery_session.session_id.
     */
    private java.util.UUID sessionId;

    /**
     * Total number of queries generated by QueryGenerationService.
     * Typically: num_categories × queries_per_category
     */
    private int queriesGenerated;

    /**
     * Total search results retrieved from all engines.
     * Before deduplication and filtering.
     */
    private int totalResultsFound;

    /**
     * Number of funding source candidates created.
     * After confidence scoring, deduplication, blacklist filtering.
     * Status: PENDING_CRAWL or SKIPPED_LOW_CONFIDENCE
     */
    private int candidatesCreated;

    /**
     * Number of duplicate domains skipped.
     * Duplicates within same session.
     */
    private int duplicatesSkipped;

    /**
     * Number of blacklisted domains skipped.
     * Based on domain_blacklist table.
     */
    private int blacklistedSkipped;

    /**
     * Number of candidates skipped due to low confidence.
     * Confidence score < 0.60 threshold.
     */
    private int lowConfidenceSkipped;

    /**
     * Number of queries that returned zero results.
     * Tracked in search_session_statistics with zero_result=true.
     * Used for adapter effectiveness analysis.
     */
    private int zeroResultCount;

    /**
     * Results count by search engine.
     * Map: SearchEngineType → result count
     * Example: {PERPLEXICA: 45, SEARXNG: 38, BRAVE: 0, SERPER: 0}
     */
    private Map<SearchEngineType, Integer> resultsByEngine;

    /**
     * Zero result queries by search engine.
     * Map: SearchEngineType → zero result count
     * Example: {BRAVE: 12, SERPER: 8, PERPLEXICA: 0, SEARXNG: 2}
     */
    private Map<SearchEngineType, Integer> zeroResultsByEngine;

    /**
     * Total workflow execution duration.
     * Includes query generation, search execution, result processing.
     */
    private Duration executionDuration;

    /**
     * Whether any adapter failures occurred.
     * True if any SearchAdapterException was thrown and caught.
     * Workflow continues with working adapters.
     */
    private boolean hasFailures;

    /**
     * List of failure messages from adapters.
     * Empty if hasFailures = false.
     * Example: ["BRAVE: 401 Unauthorized - Invalid API key", "SERPER: Connection timeout"]
     */
    @Builder.Default
    private List<String> failureMessages = List.of();
}
