package com.northstar.funding.persistence.repository;

import com.northstar.funding.domain.SearchQuery;
import org.springframework.data.jdbc.repository.query.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;

/**
 * Repository for SearchQuery entities.
 *
 * <p>Supports both hardcoded query library operations and AI-generated query persistence.
 */
@Repository
public interface SearchQueryRepository extends CrudRepository<SearchQuery, Long> {

    /**
     * Find all queries by generation session ID.
     *
     * @param sessionId the generation session ID
     * @return list of queries generated in that session
     */
    @Query("SELECT * FROM search_queries WHERE generation_session_id = :sessionId ORDER BY id")
    List<SearchQuery> findByGenerationSessionId(@Param("sessionId") Long sessionId);

    /**
     * Find all AI-generated queries created on a specific date.
     *
     * @param generationDate the date queries were generated
     * @return list of queries generated on that date
     */
    @Query("""
        SELECT * FROM search_queries
        WHERE generation_method = 'AI_GENERATED'
          AND generation_date = :generationDate
        ORDER BY id
        """)
    List<SearchQuery> findByGenerationDate(@Param("generationDate") LocalDate generationDate);

    /**
     * Find all enabled queries for a specific day of week.
     *
     * @param dayOfWeek the day of week (MONDAY, TUESDAY, etc.)
     * @return list of enabled queries for that day
     */
    @Query("""
        SELECT * FROM search_queries
        WHERE day_of_week = :dayOfWeek
          AND enabled = TRUE
        ORDER BY id
        """)
    List<SearchQuery> findEnabledByDayOfWeek(@Param("dayOfWeek") String dayOfWeek);

    /**
     * Count AI-generated queries by model.
     *
     * @param aiModelUsed the AI model name
     * @return count of queries generated by that model
     */
    @Query("""
        SELECT COUNT(*) FROM search_queries
        WHERE generation_method = 'AI_GENERATED'
          AND ai_model_used = :aiModelUsed
        """)
    long countByAiModel(@Param("aiModelUsed") String aiModelUsed);
}
