# NorthStar Funding Discovery Application Configuration
# Java 25 + Spring Boot 3.5.5 + Maven 3.9.9
# Constitutional Compliance: Mac Studio Infrastructure

spring:
  application:
    name: northstar-funding-discovery
  
  # Profile Configuration
  profiles:
    active: default
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # Flyway Database Migration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  
  # Virtual Threads (Constitutional Requirement)
  threads:
    virtual:
      enabled: true
  
  # Database Configuration (Mac Studio PostgreSQL)
  datasource:
    url: jdbc:postgresql://192.168.1.10:5432/northstar_funding
    username: northstar_user
    password: northstar_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
  
  # Security
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Server Configuration  
server:
  port: 8080
  servlet:
    context-path: /api

# Management Endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# LM Studio Configuration (Local AI - Constitutional Requirement)
# LM Studio uses OpenAI-compatible API at http://192.168.1.10:1234/v1
lm-studio:
  base-url: http://192.168.1.10:1234/v1
  model: llama-3.1-8b-instruct
  timeout-seconds: 30
  max-tokens: 500
  temperature: 0.7

# Search Engine Configuration
search:
  engines:
    # Searxng (self-hosted on Mac Studio)
    searxng:
      enabled: true
      base-url: http://192.168.1.10:8080
      max-results: 25
      timeout-seconds: 10

    # Browserbase (API-based)
    browserbase:
      enabled: true
      api-key: ${BROWSERBASE_API_KEY:}
      base-url: https://api.browserbase.com
      max-results: 25
      timeout-seconds: 15

    # Tavily (API-based)
    tavily:
      enabled: true
      api-key: ${TAVILY_API_KEY:}
      base-url: https://api.tavily.com
      max-results: 25
      timeout-seconds: 10

    # Perplexity (API-based)
    perplexity:
      enabled: true
      api-key: ${PERPLEXITY_API_KEY:}
      base-url: https://api.perplexity.ai
      max-results: 25
      timeout-seconds: 10

# Resilience4j Configuration (Fault Tolerance for Remote HTTP Calls)
resilience4j:
  circuitbreaker:
    instances:
      # Generic search engines configuration (fallback)
      searchEngines:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

      # Individual search engine configurations
      tavily:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

      searxng:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

      perplexity:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

      lmStudio:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        failureRateThreshold: 50

  retry:
    instances:
      searchEngines:
        maxAttempts: 3
        waitDuration: 1s
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.net.SocketTimeoutException
          - java.net.ConnectException

      lmStudio:
        maxAttempts: 2
        waitDuration: 500ms

# Discovery Configuration
discovery:
  schedule:
    enabled: ${DISCOVERY_SCHEDULE_ENABLED:false}
    cron: "0 0 2 * * ?" # 2 AM nightly

  # Query Library for Search Execution (Feature 003)
  # Hardcoded queries organized by day of week
  # MVP: 5-10 queries per day for Bulgaria/Balkans/Eastern Europe focus
  query-library:
    monday:
      - query: "bulgaria education grants 2025"
        tags:
          - type: GEOGRAPHY
            value: "Bulgaria"
          - type: CATEGORY
            value: "Education"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]
      - query: "eastern europe infrastructure funding opportunities"
        tags:
          - type: GEOGRAPHY
            value: "Eastern Europe"
          - type: CATEGORY
            value: "Infrastructure"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]
      - query: "balkans stem education scholarships"
        tags:
          - type: GEOGRAPHY
            value: "Balkans"
          - type: CATEGORY
            value: "STEM"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]
      - query: "romania teacher development grants 2025"
        tags:
          - type: GEOGRAPHY
            value: "Romania"
          - type: CATEGORY
            value: "Teacher Development"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]
      - query: "eu cultural heritage funding bulgaria"
        tags:
          - type: GEOGRAPHY
            value: "Bulgaria"
          - type: CATEGORY
            value: "Cultural Heritage"
          - type: AUTHORITY
            value: "EU"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]

    tuesday:
      - query: "greece nonprofit capacity building grants"
        tags:
          - type: GEOGRAPHY
            value: "Greece"
          - type: CATEGORY
            value: "Capacity Building"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]
      - query: "north macedonia youth employment programs"
        tags:
          - type: GEOGRAPHY
            value: "North Macedonia"
          - type: CATEGORY
            value: "Youth Programs"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]
      - query: "eastern europe digital skills training funding"
        tags:
          - type: GEOGRAPHY
            value: "Eastern Europe"
          - type: CATEGORY
            value: "Digital Skills"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]

    wednesday:
      - query: "bulgaria healthcare research grants"
        tags:
          - type: GEOGRAPHY
            value: "Bulgaria"
          - type: CATEGORY
            value: "Healthcare"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]
      - query: "balkans environmental sustainability funding"
        tags:
          - type: GEOGRAPHY
            value: "Balkans"
          - type: CATEGORY
            value: "Environment"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]

    thursday:
      - query: "romania arts culture grants 2025"
        tags:
          - type: GEOGRAPHY
            value: "Romania"
          - type: CATEGORY
            value: "Arts & Culture"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]
      - query: "eastern europe social innovation funding"
        tags:
          - type: GEOGRAPHY
            value: "Eastern Europe"
          - type: CATEGORY
            value: "Social Innovation"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]

    friday:
      - query: "bulgaria startup entrepreneurship grants"
        tags:
          - type: GEOGRAPHY
            value: "Bulgaria"
          - type: CATEGORY
            value: "Entrepreneurship"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]
      - query: "balkans rural development funding opportunities"
        tags:
          - type: GEOGRAPHY
            value: "Balkans"
          - type: CATEGORY
            value: "Rural Development"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]

    saturday:
      - query: "eastern europe women empowerment grants"
        tags:
          - type: GEOGRAPHY
            value: "Eastern Europe"
          - type: CATEGORY
            value: "Women's Programs"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]

    sunday:
      - query: "bulgaria eu horizon europe funding"
        tags:
          - type: GEOGRAPHY
            value: "Bulgaria"
          - type: AUTHORITY
            value: "EU"
          - type: CATEGORY
            value: "Research"
        target-engines: ["SEARXNG", "TAVILY", "PERPLEXITY"]

  # Legacy query generation templates (will be moved to Feature 004)
  query-generation:
    geography-templates:
      - "Bulgaria"
      - "Eastern Europe"
      - "Balkans"
      - "EU member states"
      - "Romania"
      - "Greece"
      - "North Macedonia"

    funding-types:
      - "grants"
      - "scholarships"
      - "fellowships"
      - "funding opportunities"
      - "financial support"

    organization-types:
      - "NGO"
      - "nonprofit"
      - "foundation"
      - "educational institutions"
      - "social enterprises"

# Logging Configuration
logging:
  level:
    com.northstar.funding: INFO
    com.northstar.funding.discovery: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    io.github.resilience4j: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

---
# Production Profile (same database, different settings)
spring:
  config:
    activate:
      on-profile: prod
  
  # Production Security (override with env vars)
  security:
    user:
      name: ${ADMIN_USERNAME:kevin}
      password: ${ADMIN_PASSWORD}
      roles: ADMIN

# Production Logging
logging:
  level:
    com.northstar.funding: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

---
# PostgreSQL TestContainers Profile
spring:
  config:
    activate:
      on-profile: postgres-test
  
  # TestContainers will override these properties dynamically
  datasource:
    url: jdbc:postgresql://localhost:5432/test  # Will be overridden by TestContainers
    username: test_user                         # Will be overridden by TestContainers
    password: test_password                     # Will be overridden by TestContainers
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5  # Smaller pool for testing
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # Let Flyway handle schema creation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  flyway:
    enabled: true  # Important: Enable migrations for TestContainers
    baseline-on-migrate: true
    locations: classpath:db/migration
    
  # Test Security (same as regular test profile)
  security:
    user:
      name: postgres-test-admin
      password: postgres-test123
      roles: ADMIN

# Enhanced logging for PostgreSQL testing and debugging
logging:
  level:
    com.northstar.funding: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
    org.testcontainers: INFO
    org.flywaydb: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
