# NorthStar Funding Discovery Application Configuration
# Java 25 + Spring Boot 3.5.5 + Maven 3.9.9
# Constitutional Compliance: Mac Studio Infrastructure

spring:
  application:
    name: northstar-funding-discovery
  
  # Profile Configuration
  profiles:
    active: default
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # Flyway Database Migration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  
  # Virtual Threads (Constitutional Requirement)
  threads:
    virtual:
      enabled: true

# Server Configuration  
server:
  port: 8080
  servlet:
    context-path: /api

# Management Endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    com.northstar.funding: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  # Default Database Configuration (Mac Studio PostgreSQL)
  datasource:
    url: jdbc:postgresql://192.168.1.10:5432/northstar_funding
    username: northstar_user
    password: northstar_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000

  # Default Security
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

---
# Production Profile (same database, different settings)
spring:
  config:
    activate:
      on-profile: prod
  
  # Production Security (override with env vars)
  security:
    user:
      name: ${ADMIN_USERNAME:kevin}
      password: ${ADMIN_PASSWORD}
      roles: ADMIN

# Production Logging
logging:
  level:
    com.northstar.funding: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test
  
  # Test Database (Embedded H2 for unit tests, TestContainers for integration)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  
  # Test Flyway
  flyway:
    enabled: false
  
  # Test Security
  security:
    user:
      name: test-admin
      password: test123
      roles: ADMIN

# Test Logging
logging:
  level:
    com.northstar.funding: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
