# NorthStar Funding Discovery Application Configuration
# Java 25 + Spring Boot 3.5.5 + Maven 3.9.9
# Constitutional Compliance: Mac Studio Infrastructure

spring:
  application:
    name: northstar-funding-discovery
  
  # Profile Configuration
  profiles:
    active: default
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  # Flyway Database Migration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  # JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  
  # Virtual Threads (Constitutional Requirement)
  threads:
    virtual:
      enabled: true

# Server Configuration  
server:
  port: 8080
  servlet:
    context-path: /api

# Management Endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    com.northstar.funding: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  # Default Database Configuration (Mac Studio PostgreSQL)
  datasource:
    url: jdbc:postgresql://192.168.1.10:5432/northstar_funding
    username: northstar_user
    password: northstar_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000

  # Default Security
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

---
# Production Profile (same database, different settings)
spring:
  config:
    activate:
      on-profile: prod
  
  # Production Security (override with env vars)
  security:
    user:
      name: ${ADMIN_USERNAME:kevin}
      password: ${ADMIN_PASSWORD}
      roles: ADMIN

# Production Logging
logging:
  level:
    com.northstar.funding: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

---
# PostgreSQL TestContainers Profile
spring:
  config:
    activate:
      on-profile: postgres-test
  
  # TestContainers will override these properties dynamically
  datasource:
    url: jdbc:postgresql://localhost:5432/test  # Will be overridden by TestContainers
    username: test_user                         # Will be overridden by TestContainers
    password: test_password                     # Will be overridden by TestContainers
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5  # Smaller pool for testing
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # Let Flyway handle schema creation
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  
  flyway:
    enabled: true  # Important: Enable migrations for TestContainers
    baseline-on-migrate: true
    locations: classpath:db/migration
    
  # Test Security (same as regular test profile)
  security:
    user:
      name: postgres-test-admin
      password: postgres-test123
      roles: ADMIN

# Enhanced logging for PostgreSQL testing and debugging
logging:
  level:
    com.northstar.funding: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
    org.testcontainers: INFO
    org.flywaydb: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
